version: '3.8'

services:
  dynatrace-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dynatrace-multi-tenant-app
    ports:
      - "5000:5000"
      - "5173:5173"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (r) => {if (r.statusCode !== 200) throw new Error(r.statusCode)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    

