version: '3.8'

services:
  dynatrace-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dynatrace-multi-tenant-app
    ports:
      - "5000:5000"
      - "5173:5173"
    environment:
      # Server Configuration
      PORT: 5000

      # Database
      DATABASE_URL: sqlite:./data/database.sqlite

      # JWT Secret
      JWT_SECRET: ${JWT_SECRET:-change-me-in-production}

      # Frontend API URL (Vite - only VITE_ prefixed variables are available)
      VITE_API_URL: ${VITE_API_URL:-http://localhost:5000/api}
    
    volumes:
      - ./data:/app/data
      - /app/node_modules
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (r) => {if (r.statusCode !== 200) throw new Error(r.statusCode)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    networks:
      - dynatrace-network

networks:
  dynatrace-network:
    driver: bridge

volumes:
  data:
    driver: local

